name: xgrains
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.5
  - geopandas>0.10,<0.14
  - matplotlib~=3.5
  - numpy~=1.23
  - pandas~=1.5
  - pygeos~=0.14
  - scikit-image~=0.19
  - stardist~=0.8
  - tifffile=2023.7.18
