name: xgrains
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.5
  - geopandas=0.10.2
  - matplotlib=3.5.3
  - numpy=1.23.5
  - pandas=1.5.0
  - pygeos=0.14
  - scikit-image=0.19.0
  - stardist=0.8.3
  - tifffile=2021.11.2
